### ISSUE TITLE
Field marked as "ref" seems to be ignored

### ISSUE THREAD

**Issue by nireak** [fauna/faunadb-importer#39]
Hi,
I have a file with lines of JSON like
{
  "id": "3924",
  "name": "Mary"
}.

I can upload it with no problems but the "id" field that I mark as ref using the parameter
--format "id:ref"
is ignored and the record gets a different ref (generated automatically) like "198480451673784842"
 
Ref
q.Ref("classes/my-class/198480451673784842")
Class
q.Ref("classes/my-class")
TS
1525544559283937
Data
{
  "id": "3924",
   "name": "Mary"
}

Am I missing something?
Thank you

**Comment by erickpintor** [comment]
Hi @nireak.

What you're seeing are Fauna's [Ref types](https://fauna.com/documentation/reference/queryapi#special-types). They are automatically generated for you as the importer loads  the data in. We currently don't support importing legacy ids in the form of Ref types as there could be a risk of collision.

Your legacy ID should be kept in the instance's data field after the import is done. If you need to search instances using the legacy id, I'd suggest to create a index for it.

I hope this helps. I'm going to close the issue but, feel free to reopen it if you need more clarification.

Cheers,

**Comment by nireak** [comment]
Thanks @erickpintor for the info! It helped!
